sudo: false
language: ruby
rvm:
  - 2.5.5
  - 2.6.2
  - ruby-head
env:
  - RUBY_VERSION_FOR_DEPLOY=2.6.2
branches:
  only:
    - master
cache: bundler
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
install:
  - travis_retry bundle install
  - travis_retry bundle update
  - gem build stisla-jekyll.gemspec
  - gem install ./stisla-jekyll-*.gem
  - bundle exec jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: gh-pages
  fqdn: sundi3yansyah.github.io/stisla-jekyll
  on:
    branch: master
    rvm: $RUBY_VERSION_FOR_DEPLOY
notifications:
  email: false
